all: 
	make -i -f MakefileCppUTest.mk 
	make -i -f MakefileUnity.mk

codeCppUTest:
	make -i -f MakefileCppUTest.mk

codeUnity:
	make -i -f MakefileUnity.mk

clean:
	make -i -f MakefileCppUTest.mk clean
	make -i -f MakefileUnity.mk clean
	
